force_update:

turn_on:
  description: Turn a dobiss output on, with optional delay in on or off
  fields:
    entity_id:
      required: true
      example: light.bureel
    brightness:
      advanced: true
      example: 25
    delayon:
      example: 10
    delayoff:
      example: 60
    from_pir:
      advanced: true
      example: True

set_hvac_temp_timer:
  fields:
    entity_id:
      example: climate.binnen
    time:
      example: 90
    temperature:
      example: 22.5

action_request:
  description: Sends an action request to the dobiss NXT server
  fields:
    address:
      required: true
      example: 1
    channel:
      required: true
      example: 1
    action:
      required: true
      example: 2
    option1:
      example: 50
    option2:
      example: 50

# from the Dobiss API info
# blijkbaar is voor temp, option1 = (target-5)*10
#{
#     "address"   : VERPLICHT, adres van de module of het NXT actie adres (>200),
#     "channel"   : VERPLICHT, module uitgang (start bij 0) of NXT uitgang nummer (start op 1),
#     "action"    : VERPLICHT, actie id (0 = uit, 1 = aan, 2 = schakelen) // zie lijst van acties
#     "option1"   : dimmer: waarde (0-100) / audio: volume (0-100) / temperatuur: stel temperatuur in of kalender
#     "option2"   : dimmer: soft start/stop (0-254) / audio: bron / temperatuur: periode
#     "delayon"   :
#     	{
#     	   "value" : 0-120,
#           "unit"  : "s","min"
#        }
#     "delayoff"  :
#        {
#           "value" : 0-120,
#           "unit"  : "s","min"
#        }
#     "condition" :
#        {
#           "id"    : ID van de logische conditie die nagekeken moet worden voor de uitvoering,
#           "operator": 'true' or 'false'
#     }
#}

status_request:
  fields:
    address:
      example: 1
    channel:
      example: 1
# from the Dobiss API info
#{
#     "address"   : OPTIONEEL, adres van de module of het NXT actie adres (>200),
#     "channel"   : OPTIONEEL, module uitgang (start bij 0) of NXT uitgang nummer (start op 1)
#}
