homeassistant:
  #customize: !include customize.yaml

default_config:

logger:
  default: info
  logs:
    custom_components.dobiss: debug
    dobissapi.dobissapi: debug
# If you need to debug uncommment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
debugpy:
  start: true
#automation: !include automations.yaml
